// Exercise library imported from the Strength Training Manual (Mladen Jovanović)
// taxonomy — 209 exercises across Olympic, Hinge, Squat, Push and Pull patterns.
// Pure data (no ids): the seed and the load-time migration assign a uid + media.
//
// Fields:
//   name        canonical exercise name (matches the workout builder's library)
//   muscle      coarse group derived from movement pattern (Legs/Hamstrings/Chest/Back/Full Body)
//   equip       primary equipment
//   difficulty  Advanced for ballistic (Olympic) lifts, else Intermediate
//   category    Ballistic | Grinding (force–velocity class from the manual)
//   pattern     movement pattern (Olympic/Hinge/Squat/Push/Pull)
//   relPct/relTo  %1RM-relative load vs a reference lift, where the manual gives one
//                 (e.g. Romanian Deadlift ≈ 75% of Squat) — drives %1RM prescription
export const EXERCISE_LIBRARY = [
  { name: "Bridge (Straight Leg Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge (Straight Leg)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge 1-Leg (Straight Leg Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge 1-Leg (Straight Leg)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Drop Downs (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Drop Downs (Slide Board)", muscle: "Hamstrings", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Drop Downs 1-Leg (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Drop Downs 1-Leg (Slide Board)", muscle: "Hamstrings", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Lift and Curl (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Lift and Curl (Slide Board)", muscle: "Hamstrings", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Lift and Curl 1-Leg (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Bridge Lift and Curl 1-Leg (Slide Board)", muscle: "Hamstrings", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "DB Romanian Deadlift", muscle: "Hamstrings", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 35, relTo: "Squat" },
  { name: "DB Romanian Deadlift 1-Arm/1-Leg (Contralateral)", muscle: "Hamstrings", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 30, relTo: "Squat" },
  { name: "DB Romanian Deadlift 1-Arm/1-Leg (Ipsilateral)", muscle: "Hamstrings", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 25, relTo: "Squat" },
  { name: "DB Romanian Deadlift 2-Arm/1-Leg", muscle: "Hamstrings", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 20, relTo: "Squat" },
  { name: "Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 100, relTo: "Deadlift" },
  { name: "Glute Bridge (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Bridge (Elevated Feet)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Bridge (Floor)", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 105, relTo: "Squat" },
  { name: "Glute Bridge 1-Leg (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Bridge 1-Leg (Elevated Feet)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Bridge 1-Leg (Floor)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Bridge 1-Leg Alternating (Floor)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Glute Ham Raise (GHR)", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Good Morning", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 50, relTo: "Squat" },
  { name: "Good Morning 1-Leg", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 30, relTo: "Squat" },
  { name: "Hip Thrust (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hip Thrust (Bench)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 100, relTo: "Squat" },
  { name: "Hip Thrust 1-Leg (Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hip Thrust 1-Leg (Bench)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hyper 45 degree", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hyper 45 degree 1-Leg", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hyper 90 degree", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Hyper 90 degree 1-Leg", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Lateral Bridge 1-Leg (Straight Leg Ball)", muscle: "Hamstrings", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Lateral Bridge 1-Leg (Straight Leg)", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Nordic Curl", muscle: "Hamstrings", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Plate Good Morning 1-Leg (Overhead)", muscle: "Hamstrings", equip: "Plates", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 10, relTo: "Squat" },
  { name: "Pull Through", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Rack Pull", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 110, relTo: "Deadlift" },
  { name: "Reverse Hyper", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Reverse Hyper 1-Leg", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Romanian Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 75, relTo: "Squat" },
  { name: "Romanian Deadlift 1-Leg", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 45, relTo: "Squat" },
  { name: "Snatch Grip Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 75, relTo: "Deadlift" },
  { name: "Sumo Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 100, relTo: "Deadlift" },
  { name: "Sumo Good Morning", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 40, relTo: "Squat" },
  { name: "Sumo Pull Through", muscle: "Hamstrings", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge" },
  { name: "Sumo Romanian Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 65, relTo: "Squat" },
  { name: "Trap Bar Romanian Deadlift", muscle: "Hamstrings", equip: "Trap Bar", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 75, relTo: "Squat" },
  { name: "Zercher Romanian Deadlift", muscle: "Hamstrings", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Hinge", relPct: 70, relTo: "Squat" },
  { name: "Clean", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 100, relTo: "Clean" },
  { name: "Clean & Jerk", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 100, relTo: "Clean and Jerk" },
  { name: "Clean (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 95, relTo: "Clean" },
  { name: "Clean (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 95, relTo: "Clean" },
  { name: "Clean (Muscle)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 60, relTo: "Clean" },
  { name: "Clean High Pull", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 80, relTo: "Clean" },
  { name: "Clean High Pull (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 75, relTo: "Clean" },
  { name: "Clean High Pull (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 75, relTo: "Clean" },
  { name: "Clean Pull", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 110, relTo: "Clean" },
  { name: "Clean Pull (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 105, relTo: "Clean" },
  { name: "Clean Pull (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 105, relTo: "Clean" },
  { name: "Power Clean", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 85, relTo: "Clean" },
  { name: "Power Clean (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 80, relTo: "Clean" },
  { name: "Power Snatch", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 85, relTo: "Snatch" },
  { name: "Power Snatch (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 80, relTo: "Snatch" },
  { name: "Snatch", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 100, relTo: "Snatch" },
  { name: "Snatch (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 95, relTo: "Snatch" },
  { name: "Snatch (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 95, relTo: "Snatch" },
  { name: "Snatch (Muscle)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 60, relTo: "Snatch" },
  { name: "Snatch Balance", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 80, relTo: "Snatch" },
  { name: "Snatch High Pull", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 80, relTo: "Snatch" },
  { name: "Snatch High Pull (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 75, relTo: "Snatch" },
  { name: "Snatch High Pull (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 75, relTo: "Snatch" },
  { name: "Snatch Pull", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 110, relTo: "Snatch" },
  { name: "Snatch Pull (Blocks)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 105, relTo: "Snatch" },
  { name: "Snatch Pull (Hang)", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 105, relTo: "Snatch" },
  { name: "Split Clean", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 90, relTo: "Clean" },
  { name: "Split Snatch", muscle: "Full Body", equip: "Barbell", difficulty: "Advanced", category: "Ballistic", pattern: "Olympic", relPct: 90, relTo: "Snatch" },
  { name: "1-Arm/1-Leg Row (Contralateral)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 25, relTo: "Pull-Up" },
  { name: "1-Arm/1-Leg Row (Ipsilateral)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 25, relTo: "Pull-Up" },
  { name: "Bar Pull Ups (Neutral)", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "Bar Pull Ups (Pronated)", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "Bar Pull Ups (Supinated)", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "Barbell Curls", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 35, relTo: "Pull-Up" },
  { name: "Bench Pull", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 70, relTo: "Pull-Up" },
  { name: "Bent Over Row", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 65, relTo: "Pull-Up" },
  { name: "Cable Row (Neutral)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 60, relTo: "Pull-Up" },
  { name: "Cable Row (Pronated)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 60, relTo: "Pull-Up" },
  { name: "Cable Row (Rope)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 60, relTo: "Pull-Up" },
  { name: "Cable Row (Supinated)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 60, relTo: "Pull-Up" },
  { name: "Chest Supported Row", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 70, relTo: "Pull-Up" },
  { name: "DB Bench Row 1-Arm", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 35, relTo: "Pull-Up" },
  { name: "DB Bench Row 2-Arm", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 30, relTo: "Pull-Up" },
  { name: "DB Bent Over Row 1-Arm (Neutral)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 35, relTo: "Pull-Up" },
  { name: "DB Bent Over Row 1-Arm (Wide)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 30, relTo: "Pull-Up" },
  { name: "DB Bent Over Row 2-Arm (Alternating)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 30, relTo: "Pull-Up" },
  { name: "DB Bent Over Row 2-Arm (Neutral)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 35, relTo: "Pull-Up" },
  { name: "DB Bent Over Row 2-Arm (Wide)", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 30, relTo: "Pull-Up" },
  { name: "DB Curls", muscle: "Back", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 20, relTo: "Pull-Up" },
  { name: "Pull Down (Neutral)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 90, relTo: "Pull-Up" },
  { name: "Pull Down (Pronated)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 90, relTo: "Pull-Up" },
  { name: "Pull Down (Supinated)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 95, relTo: "Pull-Up" },
  { name: "Pull Down (Wide)", muscle: "Back", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 85, relTo: "Pull-Up" },
  { name: "Rings Inverted Row (Neutral)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 70, relTo: "Pull-Up" },
  { name: "Rings Inverted Row (Rotation)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 70, relTo: "Pull-Up" },
  { name: "Rings Inverted Row (Wide)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 65, relTo: "Pull-Up" },
  { name: "Rings Inverted Row 1-Arm", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "Rings Pull Ups (Neutral)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 95, relTo: "Pull-Up" },
  { name: "Rings Pull Ups (Pronated)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 90, relTo: "Pull-Up" },
  { name: "Rings Pull Ups (Supinated)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 95, relTo: "Pull-Up" },
  { name: "Rings Pull Ups (Wide)", muscle: "Back", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Pull", relPct: 85, relTo: "Pull-Up" },
  { name: "Rope Climbs", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "Towel Pull-ups", muscle: "Back", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Pull" },
  { name: "1/2 Kneeling KB Press", muscle: "Chest", equip: "Landmine", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "1/2 Kneeling Land Mine Press", muscle: "Chest", equip: "Landmine", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Bench Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 100, relTo: "Bench" },
  { name: "DB Bench Press 1-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 30, relTo: "Bench" },
  { name: "DB Bench Press 2-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 35, relTo: "Bench" },
  { name: "DB Bench Press 2-Arm (Alternating)", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 30, relTo: "Bench" },
  { name: "DB Floor Press", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 30, relTo: "Bench" },
  { name: "DB Incline Bench Press 1-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 25, relTo: "Bench" },
  { name: "DB Incline Bench Press 2-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 30, relTo: "Bench" },
  { name: "DB Incline Bench Press 2-Arm (Alternating)", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 25, relTo: "Bench" },
  { name: "DB Press 1-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "DB Press 2-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "DB Press 2-Arm (Alternating)", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "DB Push Press 1-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "DB Push Press 2-Arm", muscle: "Chest", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Decline Bench Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 105, relTo: "Bench" },
  { name: "Dips", muscle: "Chest", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 120, relTo: "Bench" },
  { name: "Floor Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 90, relTo: "Bench" },
  { name: "Incline Bench Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 80, relTo: "Bench" },
  { name: "KB Press 1-Arm", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "KB Press 2-Arm", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "KB Press 2-Arm (Alternating)", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "KB Push Press 1-Arm", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "KB Push Press 2-Arm", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Log Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Military Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Press Up", muscle: "Chest", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Push Press", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Push Ups (Narrow)", muscle: "Chest", equip: "Plates", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 90, relTo: "Bench" },
  { name: "Push Ups (Normal)", muscle: "Chest", equip: "Plates", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 100, relTo: "Bench" },
  { name: "Push Ups (Wide)", muscle: "Chest", equip: "Plates", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 95, relTo: "Bench" },
  { name: "Ring Dips", muscle: "Chest", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Push", relPct: 105, relTo: "Bench" },
  { name: "Ring PushUps (Normal)", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Ring PushUps (Wide)", muscle: "Chest", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Trap Bar Press", muscle: "Chest", equip: "Trap Bar", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Yoga Push Up", muscle: "Chest", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Push" },
  { name: "Sled Backward Pushes", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Sled Cross Over Pushes", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Sled Diagonal Bakcward Pushes", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Sled Lateral Pushes", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Sled Marching", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Sled Walking Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Sled" },
  { name: "Back Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 100, relTo: "Squat" },
  { name: "Barbel Lateral Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 25, relTo: "Squat" },
  { name: "Barbell Bulgarian Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 50, relTo: "Squat" },
  { name: "Barbell Lateral Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 30, relTo: "Squat" },
  { name: "Barbell Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 40, relTo: "Squat" },
  { name: "Barbell Reverse Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 40, relTo: "Squat" },
  { name: "Barbell Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 50, relTo: "Squat" },
  { name: "Barbell Step Up", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 40, relTo: "Squat" },
  { name: "Barbell Walking Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 35, relTo: "Squat" },
  { name: "Belt Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Box Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 100, relTo: "Squat" },
  { name: "Box Squat 1-Leg", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Cable Lateral Lunges", muscle: "Legs", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 25, relTo: "Squat" },
  { name: "Cable Lateral Split Squat", muscle: "Legs", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 30, relTo: "Squat" },
  { name: "DB Bulgarian Split Squat", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 25, relTo: "Squat" },
  { name: "DB Lateral Lunges", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 10, relTo: "Squat" },
  { name: "DB Lateral Split Squat", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 15, relTo: "Squat" },
  { name: "DB Lunges", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 20, relTo: "Squat" },
  { name: "DB Reverse Lunges", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 20, relTo: "Squat" },
  { name: "DB Single Leg Squat 1-Arm", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "DB Single Leg Squat 2-Arm", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "DB Split Squat", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 25, relTo: "Squat" },
  { name: "DB Squat", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 40, relTo: "Squat" },
  { name: "DB Step Up", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 20, relTo: "Squat" },
  { name: "DB Walking Lunges", muscle: "Legs", equip: "Dumbbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 20, relTo: "Squat" },
  { name: "Front Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 85, relTo: "Squat" },
  { name: "Goblet Bulgarian Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Goblet Lateral Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Goblet Lateral Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Goblet Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Goblet Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Inclined Step Down", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Ketilebell Front Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Leg Press", muscle: "Legs", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 130, relTo: "Squat" },
  { name: "Leg Press 1-Leg", muscle: "Legs", equip: "Machine", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 70, relTo: "Squat" },
  { name: "Off Box Pistol Squat", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Overhead Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 30, relTo: "Squat" },
  { name: "Overhead Reverse Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 30, relTo: "Squat" },
  { name: "Overhead Split Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 35, relTo: "Squat" },
  { name: "Overhead Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 70, relTo: "Squat" },
  { name: "Overhead Walking Lunges", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 30, relTo: "Squat" },
  { name: "Pistol Squat", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Prisoner Squat", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Rings Bulgarian Split Squat", muscle: "Legs", equip: "Gymnastic Rings", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Slide Board Lateral Lunges", muscle: "Legs", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 20, relTo: "Squat" },
  { name: "Slide Board Reverse Lunges", muscle: "Legs", equip: "Slide Board", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 35, relTo: "Squat" },
  { name: "Speed Skater", muscle: "Legs", equip: "Bodyweight", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Sumo Back Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 90, relTo: "Squat" },
  { name: "Trap Bar Squat", muscle: "Legs", equip: "Trap Bar", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 110, relTo: "Squat" },
  { name: "Wall Squat", muscle: "Legs", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Wall Squat 1-Leg", muscle: "Legs", equip: "Fitness Ball", difficulty: "Intermediate", category: "Grinding", pattern: "Squat" },
  { name: "Zercher Squat", muscle: "Legs", equip: "Barbell", difficulty: "Intermediate", category: "Grinding", pattern: "Squat", relPct: 60, relTo: "Squat" },
]
