-- Generated by scripts/pooling/build-coach-test-migration.mjs. A31 only.
begin;
-- A31 owner-approved fictional coach-test scope. No global activation.
create table if not exists public.pooling_test_config (
 singleton boolean primary key default true check(singleton),
 enabled boolean not null default false, ends_at timestamptz not null,
 coach_ids uuid[] not null default '{}', template jsonb not null,
 check(cardinality(coach_ids)<=3)
);
create table if not exists public.pooling_test_workspaces (
 client_id text primary key references public.clients(id),
 coach_id uuid not null unique references auth.users(id),
 manifest_id text not null unique references public.pooling_manifests(id),
 notice_id text not null references public.pooling_policy_documents(id),
 expires_at timestamptz not null, revoked_at timestamptz,
 writes integer not null default 0 check(writes between 0 and 160),
 created_at timestamptz not null default now()
);
alter table public.pooling_test_config enable row level security;
alter table public.pooling_test_workspaces enable row level security;
revoke all on public.pooling_test_config,public.pooling_test_workspaces from public,anon,authenticated;
grant all on public.pooling_test_config,public.pooling_test_workspaces to service_role;

create or replace function public.pooling_module_enabled(target_client text,module text)
returns boolean language sql volatile security definer set search_path='' as $$
 select module in ('r1','r2','r3') and (
 exists(select 1 from public.pooling_runtime where singleton and r1 and case module when 'r2' then r2 when 'r3' then r3 else true end)
 or exists(select 1 from public.pooling_test_workspaces w join public.pooling_test_config x on x.singleton
 join public.clients c on c.id=w.client_id and c."coachId"=w.coach_id and c."userId"=w.coach_id
 where w.client_id=target_client and w.revoked_at is null and w.expires_at>clock_timestamp()
 and x.enabled and x.ends_at>clock_timestamp() and w.coach_id=any(x.coach_ids)))
$$;
create or replace function public.pooling_governed_client(target_client text)
returns boolean language sql stable security definer set search_path='' as $$
 select public.pooling_enabled() or exists(select 1 from public.pooling_test_workspaces where client_id=target_client)
$$;
create or replace function public.pooling_manifest_allowed(target_client text,target_manifest text)
returns boolean language sql stable security definer set search_path='' as $$
 select not exists(select 1 from public.pooling_test_workspaces where manifest_id=target_manifest and client_id<>target_client)
 and not exists(select 1 from public.pooling_test_workspaces where client_id=target_client and manifest_id<>target_manifest)
$$;
revoke all on function public.pooling_module_enabled(text,text),public.pooling_governed_client(text),public.pooling_manifest_allowed(text,text) from public,anon;
grant execute on function public.pooling_module_enabled(text,text),public.pooling_governed_client(text),public.pooling_manifest_allowed(text,text) to authenticated,service_role;

create or replace function public.pooling_client_runtime(target_client text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype;w public.pooling_test_workspaces%rowtype;active boolean;
begin
 select * into c from public.clients where id=target_client;
 if not found or auth.uid() is null or (c."coachId" is distinct from auth.uid() and c."userId" is distinct from auth.uid()) then raise exception 'forbidden';end if;
 select * into w from public.pooling_test_workspaces where client_id=target_client;
 active:=public.pooling_module_enabled(target_client,'r1');
 return jsonb_build_object('clientId',target_client,'r1',active,'r2',public.pooling_module_enabled(target_client,'r2'),'r3',public.pooling_module_enabled(target_client,'r3'),
 'governed',public.pooling_governed_client(target_client),'testOnly',w.client_id is not null,'expiresAt',w.expires_at,'revoked',w.revoked_at is not null,
 'manifestId',w.manifest_id,'noticeId',w.notice_id,'remainingWrites',case when w.client_id is not null then 160-w.writes else null end);
end $$;
create or replace function public.pooling_actor_runtime()
returns jsonb language plpgsql security definer set search_path='' as $$
declare cid text;
begin
 if auth.uid() is null then raise exception 'forbidden';end if;
 if (select count(*) from public.clients where "userId"=auth.uid())>1 then raise exception 'client_selection_required';end if;
 select id into cid from public.clients where "userId"=auth.uid();
 if cid is null then return '{"clientId":null,"governed":false,"r1":false,"r2":false,"r3":false}'::jsonb;end if;
 return public.pooling_client_runtime(cid);
end $$;
create or replace function public.pooling_test_status()
returns jsonb language plpgsql security definer set search_path='' as $$
declare x public.pooling_test_config%rowtype;w public.pooling_test_workspaces%rowtype;
begin
 if auth.uid() is null or not exists(select 1 from public.profiles where id=auth.uid() and role='coach') then raise exception 'forbidden';end if;
 select * into x from public.pooling_test_config where singleton;
 select * into w from public.pooling_test_workspaces where coach_id=auth.uid();
 return jsonb_build_object('available',coalesce(x.enabled and x.ends_at>clock_timestamp() and auth.uid()=any(x.coach_ids),false),
 'endsAt',x.ends_at,'clientId',w.client_id,'runtime',case when w.client_id is not null then public.pooling_client_runtime(w.client_id) else null end);
end $$;

create or replace function public.pooling_create_test_workspace(acknowledged boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
declare x public.pooling_test_config%rowtype;w public.pooling_test_workspaces%rowtype;actor uuid:=auth.uid();cid text;mid text;nid text;doc jsonb;expiry timestamptz;
begin
 if actor is null or not exists(select 1 from public.profiles where id=actor and role='coach') then raise exception 'forbidden';end if;
 if acknowledged is distinct from true then raise exception 'test_acknowledgement_required';end if;
 perform pg_advisory_xact_lock(hashtextextended(actor::text,6090831));
 select * into w from public.pooling_test_workspaces where coach_id=actor;
 if found then return public.pooling_client_runtime(w.client_id);end if;
 select * into x from public.pooling_test_config where singleton for share;
 if not found or not x.enabled or x.ends_at<=clock_timestamp() or not(actor=any(x.coach_ids)) then raise exception 'test_unavailable';end if;
 if (select count(*) from public.pooling_test_workspaces)>=3 then raise exception 'test_limit_reached';end if;
 cid:='fs_pool_coachtest_'||gen_random_uuid()::text;mid:=cid||'_manifest';nid:=cid||'_notice';expiry:=least(x.ends_at,clock_timestamp()+interval '7 days');
 doc:=jsonb_set(x.template,'{manifest,id}',to_jsonb(mid));
 insert into public.clients(id,"coachId","userId",name,goal,level,status,joined,notes,intake)
 values(cid,actor,actor,'FICTIONAL SOFTWARE TEST — DO NOT TRAIN','general_fitness','beginner','Active',to_char(clock_timestamp(),'YYYY-MM-DD'),
 'Software workflow testing only. The coach operates a fictional self-linked scenario; this is not a real client or clinical consent.',jsonb_build_object('testOnly',true,'source','A31'));
 insert into public.pooling_manifests(id,state,document) values(mid,'published',doc);
 insert into public.pooling_policy_documents(id,scope,market,title,body,state,evidence_reference)
 values(nid,'adult_general_fitness',cid,'Fictional software-test acknowledgement',
 'I am testing a fictional scenario under my own login. No exercise should be performed. This is not another person’s consent, a privacy policy or professional acceptance.','published','Owner-authorized A31 software testing only');
 insert into public.pooling_test_workspaces(client_id,coach_id,manifest_id,notice_id,expires_at) values(cid,actor,mid,nid,expiry);
 insert into public.pooling_scope_grants(id,client_id,scope,market,reviewer_id,evidence_reference,valid_until)
 values(cid||'_scope',cid,'adult_general_fitness',cid,'fictional-engineering-scenario','A31 fixture only; no professional authority',expiry);
 -- The actor is the new fictional self-linked tester, never another real client.
 perform public.pooling_record_consent(cid,nid,'accepted',cid||'_acknowledgement');
 return public.pooling_client_runtime(cid);
end $$;

create or replace function public.pooling_revoke_test_workspace(target_client text)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not exists(select 1 from public.pooling_test_workspaces where client_id=target_client and coach_id=auth.uid()) then raise exception 'forbidden';end if;
 perform 1 from public.clients where id=target_client for update;
 update public.pooling_test_workspaces set revoked_at=coalesce(revoked_at,clock_timestamp()) where client_id=target_client;
 return public.pooling_client_runtime(target_client);
end $$;

create or replace function public.pooling_test_scenario(target_client text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare w public.pooling_test_workspaces%rowtype;doc jsonb;at timestamptz:=clock_timestamp();source jsonb;inventory jsonb;exercise jsonb;dose jsonb;
begin
 select * into w from public.pooling_test_workspaces where client_id=target_client and coach_id=auth.uid();
 if not found then raise exception 'forbidden';end if;
 if not public.pooling_module_enabled(target_client,'r1') then raise exception 'test_unavailable';end if;
 select document into doc from public.pooling_manifests where id=w.manifest_id and state='published';
 if doc is null then raise exception 'content_revoked';end if;
 inventory:=public.pooling_source_inventory(auth.uid(),target_client);
 select v into source from jsonb_array_elements(inventory) v where v->>'source'='clients' and v->>'id'=target_client;
 exercise:=doc->'catalogue'->0;dose:=doc->'doses'->0;
 return jsonb_build_object('testOnly',true,'at',at,'source',source,'generation',(select generation from public.pooling_contexts where client_id=target_client),
 'values',jsonb_build_object('adult',true,'purpose',true,'health','no_change','equipment','[]'::jsonb,'fictional-signal',2,'support','none'),
 'proposal',jsonb_build_object('date',to_char(at at time zone 'UTC','YYYY-MM-DD'),'manifestId',w.manifest_id,
 'session',jsonb_build_object('sessionAt',at,'timeZone','UTC','request',jsonb_build_object('setting','home','level','beginner','roles',jsonb_build_array(jsonb_build_object('id','main','required',true)),'budgetSeconds',10)),
 'selection',jsonb_build_array(jsonb_build_object('occurrenceId','fictional-occ1','role','main','exerciseId',exercise->>'id','exerciseRevision',1,'doseId',dose->>'id','doseRevision',1))));
end $$;

create or replace function public.pooling_protect_test_identity()
returns trigger language plpgsql security definer set search_path='' as $$
begin
 if exists(select 1 from public.pooling_test_workspaces where client_id=old.id) then
  if TG_OP='DELETE' or to_jsonb(old) is distinct from to_jsonb(new) then raise exception 'fictional_identity_locked';end if;
 end if;
 if TG_OP='DELETE' then return old;end if;return new;
end $$;
drop trigger if exists pooling_test_identity on public.clients;
create trigger pooling_test_identity before update or delete on public.clients for each row execute function public.pooling_protect_test_identity();

create or replace function public.pooling_test_write_limit()
returns trigger language plpgsql security definer set search_path='' as $$
declare row_data jsonb:=to_jsonb(new);cid text;open_sessions integer;write_cap integer;
begin
 cid:=coalesce(row_data->>'client_id',row_data->>'clientId');
 if cid is null and row_data ? 'assignment_id' then select client_id into cid from public.pooling_assignments where id=(row_data->>'assignment_id')::bigint;end if;
 if cid is null and row_data ? 'draft_id' then select client_id into cid from public.pooling_drafts where id=(row_data->>'draft_id')::bigint;end if;
 if cid is null and row_data ? 'week_id' then select client_id into cid from public.pooling_week_reviews where id=(row_data->>'week_id')::bigint;end if;
 if cid is not null and exists(select 1 from public.pooling_test_workspaces where client_id=cid) then
  -- Never let results/corrections consume the last Stop slot for an open session.
  -- Serialize even direct privileged test inserts against the per-workspace cap.
  perform 1 from public.pooling_test_workspaces where client_id=cid for update;
  select count(*) into open_sessions from public.pooling_assignments a where a.client_id=cid and
   (select e.kind from public.pooling_execution_events e where e.assignment_id=a.id and e.kind<>'actual' order by e.id desc limit 1) in ('start','pause','resume');
  write_cap:=least(140,160-open_sessions);
  if TG_TABLE_NAME='pooling_execution_events' then
   if row_data->>'kind' in ('stop','complete') then write_cap:=160;
   elsif row_data->>'kind'='actual' then write_cap:=160-open_sessions;
   elsif row_data->>'kind'='start' then write_cap:=least(140,159-open_sessions);end if;
  end if;
  update public.pooling_test_workspaces set writes=writes+1 where client_id=cid and writes<write_cap;
  if not found then raise exception 'test_limit_reached';end if;
 end if;
 return new;
end $$;
do $$declare t text;begin
 for t in select distinct c.table_name from information_schema.columns c join information_schema.tables b using(table_schema,table_name) where c.table_schema='public' and b.table_type='BASE TABLE' and c.column_name in ('client_id','clientId','assignment_id','draft_id','week_id') and c.table_name not in ('pooling_test_workspaces') loop
  execute format('drop trigger if exists pooling_test_row_limit on public.%I',t);
  execute format('create trigger pooling_test_row_limit before insert on public.%I for each row execute function public.pooling_test_write_limit()',t);
 end loop;
end $$;
revoke all on function public.pooling_client_runtime(text),public.pooling_actor_runtime(),public.pooling_test_status(),public.pooling_create_test_workspace(boolean),public.pooling_revoke_test_workspace(text),public.pooling_test_scenario(text) from public,anon;
grant execute on function public.pooling_client_runtime(text),public.pooling_actor_runtime(),public.pooling_test_status(),public.pooling_create_test_workspace(boolean),public.pooling_revoke_test_workspace(text),public.pooling_test_scenario(text) to authenticated;
revoke all on function public.pooling_protect_test_identity(),public.pooling_test_write_limit() from public,anon,authenticated;

drop policy if exists athlete_reads_self on public.clients;
create policy athlete_reads_self on public.clients for select to authenticated using ("userId"=auth.uid() and not public.pooling_governed_client(id));
drop policy if exists athlete_reads_assessments on public.assessments;
create policy athlete_reads_assessments on public.assessments for select to authenticated using (public.pooling_linked("clientId") and not public.pooling_governed_client("clientId"));
drop policy if exists athlete_reads_screenings on public.screenings;
create policy athlete_reads_screenings on public.screenings for select to authenticated using (public.pooling_linked("clientId") and not public.pooling_governed_client("clientId"));
do $$ declare t text; begin
 foreach t in array array['sessions','logs','wellness','srpe','resistance','cardio','wearable','concerns','prescriptions','workouts'] loop
   execute format('drop policy if exists athlete_reads on public.%I',t);
   execute format('create policy athlete_reads on public.%I for select to authenticated using (public.pooling_linked("clientId") and not public.pooling_governed_client("clientId"))',t);
 end loop;
end $$;


create or replace function public.pooling_submit_report(
  target_client text, expected_generation bigint, operation_key text,
  report_field text, report_value jsonb, effective_at timestamptz
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  c public.clients%rowtype; ctx public.pooling_contexts%rowtype;
  prior public.pooling_reports%rowtype; report_id bigint; actor uuid := auth.uid();
begin
  if actor is null then raise exception 'forbidden'; end if;
  if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
  select * into c from public.clients where id=target_client for update;
  if not found or (c."coachId" is distinct from actor and c."userId" is distinct from actor) then raise exception 'forbidden'; end if;
  if length(operation_key) not between 8 and 200 or operation_key is null then raise exception 'invalid_operation_key'; end if;
  if report_field is null or report_field not in ('healthChange','sleep','stress','fatigue','soreness','equipment','budgetSeconds') then raise exception 'invalid_field'; end if;
  if report_value is null or report_value='null'::jsonb or octet_length(report_value::text)>16384 or effective_at is null or not isfinite(effective_at) or effective_at > clock_timestamp() then raise exception 'invalid_report'; end if;
  if report_field='healthChange' and report_value not in ('"changed"'::jsonb,'"no_change"'::jsonb,'"declined"'::jsonb) then raise exception 'invalid_health_change'; end if;
  if report_field in ('sleep','stress','fatigue','soreness') and
    (jsonb_typeof(report_value)<>'number' or report_value::text::numeric < 1 or report_value::text::numeric > 7 or trunc(report_value::text::numeric) <> report_value::text::numeric)
    then raise exception 'invalid_wellness'; end if;
  if report_field='budgetSeconds' and (jsonb_typeof(report_value)<>'number' or report_value::text::numeric <= 0) then raise exception 'invalid_budget'; end if;
  if report_field='equipment' and jsonb_typeof(report_value)<>'array' then raise exception 'invalid_equipment'; end if;
  if report_field='equipment' then
   if exists(select 1 from jsonb_array_elements(report_value) v where jsonb_typeof(v)<>'string' or length(trim(v #>> '{}')) not between 1 and 100)
      or (select count(distinct v) from jsonb_array_elements(report_value) v)<>jsonb_array_length(report_value) then raise exception 'invalid_equipment';end if;
  end if;
  select * into prior from public.pooling_reports r where r.client_id=target_client and r.actor_id=actor and r.operation_key=pooling_submit_report.operation_key;
  if found then
    if prior.field<>report_field or prior.value<>report_value or prior.effective_at<>pooling_submit_report.effective_at then raise exception 'idempotency_conflict'; end if;
    return jsonb_build_object('id',prior.id,'generation',prior.generation,'status','saved');
  end if;
  insert into public.pooling_contexts(client_id) values(target_client) on conflict do nothing;
  select * into ctx from public.pooling_contexts where client_id=target_client for update;
  if expected_generation is distinct from ctx.generation then raise exception 'stale_context'; end if;
  update public.pooling_contexts set generation=generation+1,
    held=held or (report_field='healthChange' and report_value <> '"no_change"'::jsonb), updated_at=now()
    where client_id=target_client returning * into ctx;
  insert into public.pooling_reports(client_id, actor_id,reporter_kind,field,value,effective_at,generation,operation_key)
    values(target_client,actor,case when c."coachId"=actor then 'coach_entry' else 'client_report' end,
    report_field,report_value,pooling_submit_report.effective_at,ctx.generation,pooling_submit_report.operation_key)
    returning id into report_id;
  return jsonb_build_object('id',report_id,'generation',ctx.generation,'status','saved');
end $$;

create or replace function public.pooling_save_draft(
  target_client text, expected_generation bigint, operation_key text, proposal jsonb, parent_id bigint default null
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  c public.clients%rowtype; ctx public.pooling_contexts%rowtype; prior public.pooling_drafts%rowtype;
  parent public.pooling_drafts%rowtype; draft_id bigint; actor uuid := auth.uid(); next_revision bigint := 1;
begin
  if actor is null then raise exception 'forbidden'; end if;
  if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
  select * into c from public.clients where id=target_client for update;
  if not found or c."coachId" is distinct from actor then raise exception 'forbidden'; end if;
  if operation_key is null or length(operation_key) not between 8 and 200 then raise exception 'invalid_operation_key'; end if;
  if proposal is null or jsonb_typeof(proposal)<>'object' or octet_length(proposal::text)>262144 then raise exception 'invalid_proposal'; end if;
  if proposal ?| array['approval','assignment','approvedBy','assigned','coachId','actorId'] then raise exception 'protected_field'; end if;
  select * into prior from public.pooling_drafts d where d.client_id=target_client and d.actor_id=actor and d.operation_key=pooling_save_draft.operation_key;
  if found then
    if prior.proposal<>pooling_save_draft.proposal or prior.parent_id is distinct from pooling_save_draft.parent_id then raise exception 'idempotency_conflict'; end if;
    return jsonb_build_object('id',prior.id,'revision',prior.revision,'status','saved','state','draft');
  end if;
  insert into public.pooling_contexts(client_id) values(target_client) on conflict do nothing;
  select * into ctx from public.pooling_contexts where client_id=target_client for update;
  if expected_generation is distinct from ctx.generation then raise exception 'stale_context'; end if;
  if parent_id is not null then
    select * into parent from public.pooling_drafts d where d.id=pooling_save_draft.parent_id and d.client_id=target_client;
    if not found then raise exception 'invalid_parent'; end if;
    if exists(select 1 from public.pooling_drafts d where d.parent_id=parent.id) then raise exception 'draft_conflict'; end if;
    next_revision := parent.revision+1;
  end if;
  insert into public.pooling_drafts(client_id,actor_id,revision,context_generation,parent_id,proposal,operation_key)
    values(target_client,actor,next_revision,ctx.generation,pooling_save_draft.parent_id,pooling_save_draft.proposal,pooling_save_draft.operation_key)
    returning id into draft_id;
  return jsonb_build_object('id',draft_id,'revision',next_revision,'status','saved','state','draft');
end $$;

create or replace function public.pooling_approve(
 target_client text, draft_id bigint, decision_id bigint, expected_generation bigint, operation_key text
) returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; ctx public.pooling_contexts%rowtype; d public.pooling_drafts%rowtype;
 v public.pooling_decisions%rowtype; m public.pooling_manifests%rowtype; a public.pooling_assignments%rowtype; actor uuid:=auth.uid();
begin
 if actor is null then raise exception 'forbidden'; end if;
 select * into c from public.clients where id=target_client for update;
 if not found or c."coachId" is distinct from actor then raise exception 'forbidden'; end if;
 if operation_key is null or length(operation_key) not between 8 and 200 then raise exception 'invalid_operation_key'; end if;
 select * into a from public.pooling_assignments x where x.coach_id=actor and x.client_id=target_client and x.operation_key=pooling_approve.operation_key;
 if found then
   if a.draft_id is distinct from pooling_approve.draft_id or a.decision_id is distinct from pooling_approve.decision_id or a.context_generation is distinct from expected_generation then raise exception 'idempotency_conflict'; end if;
   return jsonb_build_object('assignmentId',a.id,'draftId',a.draft_id,'approvedAt',a.approved_at,'status','committed');
 end if;
 select * into a from public.pooling_assignments x where x.coach_id=actor and x.client_id=target_client and x.draft_id=pooling_approve.draft_id;
 if found then
   if a.decision_id is distinct from pooling_approve.decision_id or a.context_generation is distinct from expected_generation then raise exception 'draft_conflict';end if;
   return jsonb_build_object('assignmentId',a.id,'draftId',a.draft_id,'approvedAt',a.approved_at,'status','committed');
 end if;
 if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 if not found or ctx.generation is distinct from expected_generation then raise exception 'stale_context'; end if;
 if ctx.held then raise exception 'context_held'; end if;
 select * into d from public.pooling_drafts x where x.id=pooling_approve.draft_id and x.client_id=target_client;
 if not found or d.context_generation<>ctx.generation then raise exception 'stale_draft'; end if;
 if exists(select 1 from public.pooling_drafts x where x.parent_id=d.id) then raise exception 'stale_draft'; end if;
 select * into v from public.pooling_decisions x where x.id=pooling_approve.decision_id and x.draft_id=d.id;
 if not found or v.context_generation<>ctx.generation or v.valid_until<=clock_timestamp() then raise exception 'decision_unavailable'; end if;
 select * into m from public.pooling_manifests where id=v.manifest_id for share;
 if not found or m.state<>'published' then raise exception 'content_revoked'; end if;
 -- Added by decision-gateway migration. Fail closed if the gateway is absent.
 perform public.pooling_assert_decision_current(c."coachId",target_client,d.id,v.id);
 if v.result->>'completeness' is distinct from 'ready_for_coach_review' or v.result->>'sessionState' is distinct from 'eligible_for_coach_review' or jsonb_typeof(v.result->'blocks') is distinct from 'array' then raise exception 'required_gap'; end if;
 if jsonb_array_length(v.result->'blocks')<1 then raise exception 'required_gap'; end if;
 insert into public.pooling_assignments(client_id,draft_id,decision_id,coach_id,context_generation,operation_key)
 values(target_client,d.id,v.id,actor,ctx.generation,pooling_approve.operation_key) returning * into a;
 return jsonb_build_object('assignmentId',a.id,'draftId',a.draft_id,'approvedAt',a.approved_at,'status','committed');
end $$;

create or replace function public.pooling_execution(
 assignment_id bigint, expected_generation bigint, operation_key text, event_kind text, event_payload jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.pooling_assignments%rowtype; c public.clients%rowtype; ctx public.pooling_contexts%rowtype;
 v public.pooling_decisions%rowtype; m public.pooling_manifests%rowtype; prior public.pooling_execution_events%rowtype;
 last_kind text; event_id bigint; actor uuid:=auth.uid(); session_source record; target_block jsonb;
begin
 if actor is null then raise exception 'forbidden'; end if;
 select * into a from public.pooling_assignments x where x.id=pooling_execution.assignment_id;
 if not found then raise exception 'forbidden'; end if;
 select * into c from public.clients where id=a.client_id for update;
 if c."coachId" is distinct from actor and c."userId" is distinct from actor then raise exception 'forbidden'; end if;
 if operation_key is null or length(operation_key) not between 8 and 200 then raise exception 'invalid_operation_key'; end if;
 if event_kind is null or event_kind not in ('start','pause','resume','stop','complete','actual') or event_payload is null or jsonb_typeof(event_payload)<>'object' then raise exception 'invalid_event'; end if;
 if octet_length(event_payload::text)>65536 then raise exception 'protected_field'; end if;
 if event_kind in ('start','resume') then
   if exists(select 1 from jsonb_object_keys(event_payload) k where k<>'healthChange') then raise exception 'protected_field'; end if;
 elsif event_kind='actual' then
   if exists(select 1 from jsonb_object_keys(event_payload) k where k not in ('occurrenceId','setIndex','actual','unit','side','loadKg','effort','effortMethod','supersedes','correctionReason','performedAt')) then raise exception 'protected_field'; end if;
   if jsonb_typeof(event_payload->'occurrenceId') is distinct from 'string' or jsonb_typeof(event_payload->'setIndex') is distinct from 'number'
     or (event_payload->>'setIndex')::numeric<>trunc((event_payload->>'setIndex')::numeric) or (event_payload->>'setIndex')::numeric<1
     or jsonb_typeof(event_payload->'actual') is distinct from 'number' or (event_payload->>'actual')::numeric<0
     or event_payload->>'unit' not in ('repetitions','seconds') or event_payload->>'unit' is null then raise exception 'invalid_actual'; end if;
   if event_payload ? 'loadKg' and (jsonb_typeof(event_payload->'loadKg') is distinct from 'number' or (event_payload->>'loadKg')::numeric<0) then raise exception 'invalid_actual'; end if;
   if event_payload ?| array['effort','effortMethod'] and (jsonb_typeof(event_payload->'effort') is distinct from 'number' or jsonb_typeof(event_payload->'effortMethod') is distinct from 'string' or length(trim(event_payload->>'effortMethod')) not between 1 and 100) then raise exception 'invalid_actual'; end if;
   if event_payload ? 'performedAt' and (jsonb_typeof(event_payload->'performedAt') is distinct from 'string' or (event_payload->>'performedAt')::timestamptz>clock_timestamp() or not isfinite((event_payload->>'performedAt')::timestamptz)) then raise exception 'invalid_actual'; end if;
 else
   if event_payload<>'{}'::jsonb then raise exception 'protected_field'; end if;
 end if;
 select * into prior from public.pooling_execution_events x where x.actor_id=actor and x.assignment_id=a.id and x.operation_key=pooling_execution.operation_key;
 if found then
   if prior.kind<>event_kind or prior.payload<>event_payload then raise exception 'idempotency_conflict'; end if;
   return jsonb_build_object('eventId',prior.id,'status','committed');
 end if;
 select kind into last_kind from public.pooling_execution_events x where x.assignment_id=a.id and x.kind<>'actual' order by id desc limit 1;
 if event_kind in ('start','resume') then
   if public.pooling_module_enabled(a.client_id,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
   if (event_kind='start' and last_kind is not null) or (event_kind='resume' and last_kind is distinct from 'pause') then raise exception 'invalid_transition'; end if;
   select * into ctx from public.pooling_contexts where client_id=a.client_id for update;
   if ctx.generation is distinct from expected_generation or a.context_generation is distinct from ctx.generation then raise exception 'stale_context'; end if;
   if ctx.held then raise exception 'context_held'; end if;
   if event_payload->>'healthChange' is distinct from 'no_change' then raise exception 'health_check_required'; end if;
   select * into v from public.pooling_decisions where id=a.decision_id;
   select * into m from public.pooling_manifests where id=v.manifest_id for share;
   if m.state is distinct from 'published' or v.valid_until<=clock_timestamp() then raise exception 'content_revoked'; end if;
   perform public.pooling_assert_decision_current(c."coachId",a.client_id,a.draft_id,a.decision_id);
   select * into session_source from public.pooling_source_snapshots where draft_id=a.draft_id;
   if to_char(clock_timestamp() at time zone (session_source.context_input->>'timeZone'),'YYYY-MM-DD') is distinct from to_char((session_source.context_input->>'sessionAt')::timestamptz at time zone (session_source.context_input->>'timeZone'),'YYYY-MM-DD') then raise exception 'session_mismatch'; end if;
 elsif event_kind in ('pause','complete','actual') and (last_kind is null or last_kind not in ('start','resume','pause')) and not (event_kind='actual' and last_kind in ('stop','complete') and event_payload ? 'performedAt') then
   raise exception 'invalid_transition';
 end if;
 if event_kind='stop' and (last_kind is null or last_kind not in ('start','resume','pause')) then raise exception 'invalid_transition'; end if;
 if event_kind='actual' then
   select * into v from public.pooling_decisions where id=a.decision_id;
   select b into target_block from jsonb_array_elements(v.result->'blocks') b where b->>'occurrenceId'=event_payload->>'occurrenceId';
   if target_block is null or (event_payload->>'setIndex')::numeric > (target_block->'dose'->'prescription'->>'sets')::numeric
      or event_payload->>'unit' is distinct from (case when target_block->'dose'->'prescription'->>'mode'='repetitions' then 'repetitions' else 'seconds' end)
      or (event_payload->>'unit'='repetitions' and (event_payload->>'actual')::numeric<>trunc((event_payload->>'actual')::numeric)) then raise exception 'invalid_actual'; end if;
   if (target_block->'dose'->'prescription'->>'sideMultiplier')::int=2 then
     if event_payload->>'side' is null or event_payload->>'side' not in ('left','right') then raise exception 'invalid_actual'; end if;
   elsif coalesce(event_payload->>'side','not_applicable')<>'not_applicable' then raise exception 'invalid_actual'; end if;
   if event_payload ? 'performedAt' and ((event_payload->>'performedAt')::timestamptz < (select min(recorded_at) from public.pooling_execution_events e where e.assignment_id=a.id and e.kind='start')
     or (last_kind in ('stop','complete') and (event_payload->>'performedAt')::timestamptz > (select max(recorded_at) from public.pooling_execution_events e where e.assignment_id=a.id and e.kind in ('stop','complete')))) then raise exception 'invalid_actual'; end if;
   if event_payload ? 'supersedes' then
     if jsonb_typeof(event_payload->'supersedes') is distinct from 'number' or (event_payload->>'supersedes')::numeric<1 or (event_payload->>'supersedes')::numeric<>trunc((event_payload->>'supersedes')::numeric)
       or jsonb_typeof(event_payload->'correctionReason') is distinct from 'string' or length(trim(event_payload->>'correctionReason')) not between 1 and 1000 then raise exception 'invalid_actual'; end if;
     if not exists(select 1 from public.pooling_execution_events e where e.id=(event_payload->>'supersedes')::bigint and e.assignment_id=a.id and e.kind='actual'
        and e.payload->>'occurrenceId'=event_payload->>'occurrenceId' and e.payload->>'setIndex'=event_payload->>'setIndex' and coalesce(e.payload->>'side','not_applicable')=coalesce(event_payload->>'side','not_applicable'))
        or exists(select 1 from public.pooling_execution_events e where e.assignment_id=a.id and e.payload->>'supersedes'=event_payload->>'supersedes') then raise exception 'invalid_actual'; end if;
   elsif exists(select 1 from public.pooling_execution_events e where e.assignment_id=a.id and e.kind='actual' and e.payload->>'occurrenceId'=event_payload->>'occurrenceId'
     and e.payload->>'setIndex'=event_payload->>'setIndex' and coalesce(e.payload->>'side','not_applicable')=coalesce(event_payload->>'side','not_applicable')) then raise exception 'correction_required';
   end if;
 end if;
 insert into public.pooling_execution_events(assignment_id,actor_id,kind,payload,operation_key)
 values(a.id,actor,event_kind,event_payload,pooling_execution.operation_key) returning id into event_id;
 return jsonb_build_object('eventId',event_id,'status','committed');
end $$;

create or replace function public.pooling_decision_input(verified_actor uuid,target_client text,target_draft bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; ctx public.pooling_contexts%rowtype; d public.pooling_drafts%rowtype;
 s public.pooling_source_snapshots%rowtype; m public.pooling_manifests%rowtype; token text;
begin
 select * into c from public.clients where id=target_client for update;
 if not found or verified_actor is null or c."coachId" is distinct from verified_actor then raise exception 'forbidden'; end if;
 if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 if not found then raise exception 'source_unavailable'; end if;
 select * into d from public.pooling_drafts where id=target_draft and client_id=target_client;
 if not found or d.context_generation<>ctx.generation then raise exception 'stale_context'; end if;
 if exists(select 1 from public.pooling_drafts child where child.parent_id=d.id) then raise exception 'stale_draft';end if;
 select * into s from public.pooling_source_snapshots where draft_id=target_draft and client_id=target_client for share;
 if not found or not s.verified or s.generation<>ctx.generation or s.valid_until<=clock_timestamp() then raise exception 'source_unavailable'; end if;
 select * into m from public.pooling_manifests where id=s.manifest_id for share;
 if not public.pooling_manifest_allowed(target_client,m.id) then raise exception 'test_scope_mismatch';end if;
 if not found or m.state<>'published' then raise exception 'content_revoked'; end if;
 if d.proposal->>'date' is distinct from to_char((s.context_input->>'sessionAt')::timestamptz at time zone (s.context_input->>'timeZone'),'YYYY-MM-DD') then raise exception 'session_mismatch'; end if;
 token:=encode(sha256(convert_to(jsonb_build_object('draft',d.proposal,'generation',ctx.generation,'held',ctx.held,'source',to_jsonb(s),'manifest',m.document)::text,'UTF8')),'hex');
 return jsonb_build_object('clientId',target_client,'generation',ctx.generation,'held',ctx.held,'sourceToken',token,
  'draft',jsonb_build_object('id',d.id,'clientId',d.client_id,'contextGeneration',d.context_generation,'selection',d.proposal->'selection'),
  'contextInput',s.context_input,'sessionRequest',s.session_request,'modulePolicy',m.document->'modulePolicy',
  'catalogue',m.document->'catalogue','doses',m.document->'doses',
  'manifest',(m.document->'manifest') || jsonb_build_object('id',m.id,'state',m.state));
end $$;

create or replace function public.pooling_confirm_source(target_client text,expected_generation bigint,operation_key text,observation jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); inventory jsonb; ctx public.pooling_contexts%rowtype; prior public.pooling_confirmations%rowtype; receipt_id bigint;
begin
 if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
 inventory:=public.pooling_source_inventory(actor,target_client);
 if operation_key is null or length(operation_key) not between 8 and 200 then raise exception 'invalid_operation_key'; end if;
 if observation is null or jsonb_typeof(observation)<>'object' or octet_length(observation::text)>16384 then raise exception 'invalid_confirmation'; end if;
 if exists(select 1 from jsonb_object_keys(observation) k where k not in ('key','source','sourceId','sourceToken','state','value','unit','protocol','side','effectiveAt','evidenceReference','supersedes','sessionAt')) then raise exception 'protected_field'; end if;
 if exists(select 1 from unnest(array['key','source','sourceId','sourceToken','unit','protocol','evidenceReference']) k
   where jsonb_typeof(observation->k) is distinct from 'string' or length(trim(observation->>k)) not between 1 and 1000) then raise exception 'invalid_confirmation'; end if;
 if observation->>'state' is null or observation->>'state' not in ('observed_present','assessed_absent','measured','reported','unknown','not_assessed','not_applicable')
   or observation->>'side' is null or observation->>'side' not in ('left','right','bilateral','midline','not_applicable') or not observation ? 'value'
   or observation->>'effectiveAt' is null or (observation->>'effectiveAt')::timestamptz>clock_timestamp() then raise exception 'invalid_confirmation'; end if;
 if observation->>'state' in ('unknown','not_assessed','not_applicable') and observation->'value'<>'null'::jsonb then raise exception 'invalid_confirmation'; end if;
 if observation->>'state'='observed_present' and observation->'value' is distinct from 'true'::jsonb then raise exception 'invalid_confirmation'; end if;
 if observation->>'state'='assessed_absent' and observation->'value' is distinct from 'false'::jsonb then raise exception 'invalid_confirmation'; end if;
 if observation->>'state' in ('measured','reported') and observation->'value'='null'::jsonb then raise exception 'invalid_confirmation'; end if;
 select * into prior from public.pooling_confirmations p where p.actor_id=actor and p.client_id=target_client and p.operation_key=pooling_confirm_source.operation_key;
 if found then
   if prior.observation<>pooling_confirm_source.observation then raise exception 'idempotency_conflict'; end if;
   return jsonb_build_object('id',prior.id,'generation',prior.generation,'status','committed');
 end if;
 if not exists(select 1 from jsonb_array_elements(inventory) s where s->>'source'=observation->>'source' and s->>'id'=observation->>'sourceId' and s->>'token'=observation->>'sourceToken' and s->>'status'='loaded') then raise exception 'source_changed'; end if;
 if observation->>'supersedes' is not null and not exists(select 1 from public.pooling_confirmations p where p.id::text=pooling_confirm_source.observation->>'supersedes' and p.client_id=target_client and p.observation->>'key'=pooling_confirm_source.observation->>'key' and p.observation->>'source'=pooling_confirm_source.observation->>'source' and p.observation->>'side'=pooling_confirm_source.observation->>'side') then raise exception 'invalid_parent'; end if;
 insert into public.pooling_contexts(client_id) values(target_client) on conflict do nothing;
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 if ctx.generation is distinct from expected_generation then raise exception 'stale_context'; end if;
 update public.pooling_contexts set generation=generation+1,updated_at=now() where client_id=target_client returning * into ctx;
 insert into public.pooling_confirmations(client_id,actor_id,observation,generation,operation_key)
 values(target_client,actor,pooling_confirm_source.observation,ctx.generation,pooling_confirm_source.operation_key) returning id into receipt_id;
 return jsonb_build_object('id',receipt_id,'generation',ctx.generation,'status','committed');
end $$;

create or replace function public.pooling_source_bundle(verified_actor uuid,target_client text,target_draft bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare inventory jsonb; d public.pooling_drafts%rowtype; m public.pooling_manifests%rowtype; ctx public.pooling_contexts%rowtype; result jsonb; governance jsonb;
begin
 if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
 inventory:=public.pooling_source_inventory(verified_actor,target_client);
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 select * into d from public.pooling_drafts where id=target_draft and client_id=target_client;
 if not found or ctx.generation is null or d.context_generation<>ctx.generation then raise exception 'stale_context'; end if;
 select * into m from public.pooling_manifests where id=d.proposal->>'manifestId' for share;
 if not public.pooling_manifest_allowed(target_client,m.id) then raise exception 'test_scope_mismatch';end if;
 if not found or m.state<>'published' then raise exception 'content_revoked'; end if;
 governance:=public.pooling_governance_bundle(verified_actor,target_client,m.document->'modulePolicy'->>'scope',(d.proposal->'session'->>'sessionAt')::timestamptz);
 result:=jsonb_build_object('clientId',target_client,'generation',ctx.generation,'held',ctx.held,'draftId',d.id,'sources',inventory,
   'confirmations',(select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'clientId',p.client_id,'observation',p.observation,'confirmedBy',p.actor_id,'confirmedAt',p.confirmed_at,'recordedAt',p.confirmed_at) order by p.id),'[]') from public.pooling_confirmations p where p.client_id=target_client),
   'restrictions',governance->'restrictions','purposeAuthority',governance->'purposeAuthority','authorityValidUntil',governance->'authorityValidUntil','session',d.proposal->'session','modulePolicy',m.document->'modulePolicy',
   'manifest',(m.document->'manifest')||jsonb_build_object('id',m.id,'state',m.state));
 -- Governance ledger is server-owned; neither client input nor a source
 -- confirmation can manufacture consent, scope grants or a restriction resolution.
 return result||jsonb_build_object('sourceBundleToken',encode(sha256(convert_to(result::text,'UTF8')),'hex'),'cutoff',clock_timestamp());
end $$;

create or replace function public.pooling_guard_legacy_write() returns trigger language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; cid text; actor uuid:=auth.uid(); before_row jsonb; after_row jsonb;
begin
 if actor is null then if TG_OP='DELETE' then return old; else return new; end if; end if;
 before_row:=case when TG_OP='INSERT' then '{}'::jsonb else to_jsonb(old) end;
 after_row:=case when TG_OP='DELETE' then '{}'::jsonb else to_jsonb(new) end;
 cid:=coalesce(after_row->>'clientId',before_row->>'clientId');
 if not public.pooling_governed_client(cid) then if TG_OP='DELETE' then return old;else return new;end if;end if;
 select * into c from public.clients where id=cid for update;
 if not found or (c."coachId" is distinct from actor and c."userId" is distinct from actor) then raise exception 'forbidden'; end if;
 if TG_OP='UPDATE' and before_row->>'clientId' is distinct from after_row->>'clientId' then raise exception 'client_reparent_forbidden'; end if;
 if TG_TABLE_NAME='workouts' then
   if TG_OP='UPDATE' and before_row->>'status'='in_progress' and after_row->>'status'='stopped' and (before_row-'status')=(after_row-'status') then return new; end if;
   raise exception 'governed_workflow_required';
 end if;
 if TG_TABLE_NAME='prescriptions' then raise exception 'governed_workflow_required'; end if;
 if c."coachId" is distinct from actor then raise exception 'guarded_report_required'; end if;
 if TG_OP<>'DELETE' and after_row->>'coachId' is distinct from c."coachId"::text then raise exception 'protected_field'; end if;
 if TG_OP='DELETE' then return old; else return new; end if;
end $$;

create or replace function public.pooling_athlete_snapshot() returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; result jsonb;
begin
 if auth.uid() is null then raise exception 'forbidden'; end if;
 -- Multiple links need explicit client selection, not an arbitrary first match.
 if (select count(*) from public.clients where "userId"=auth.uid())>1 then raise exception 'client_selection_required'; end if;
 select * into c from public.clients where "userId"=auth.uid();
 if not found then return '{"client":null}'; end if;
 if not public.pooling_governed_client(c.id) then raise exception 'feature_disabled';end if;
 result:=jsonb_build_object('client',jsonb_build_object('id',c.id,'coachId',c."coachId",'userId',c."userId",'name',c.name,'goal',c.goal,'level',c.level,'status',c.status),
   'assignments',public.pooling_read_assignments(c.id),'plans','[]'::jsonb,'exercises','[]'::jsonb,'prescriptions','[]'::jsonb,'workouts','[]'::jsonb,'screenings','[]'::jsonb,'assessments','[]'::jsonb,'wellness','[]'::jsonb,'srpe','[]'::jsonb,'sessions','[]'::jsonb,'wearable','[]'::jsonb,'wearable_tokens','[]'::jsonb,'maxes','[]'::jsonb,
   'sourceAvailability','protected_projection','message','Legacy private source records are not part of this client projection. Use attributed reports and coach-reviewed assignments.');
 return result;
end $$;

create or replace function public.pooling_review_workspace(target_client text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype;
begin
 select * into c from public.clients where id=target_client;
 if not found or auth.uid() is null or c."coachId" is distinct from auth.uid() then raise exception 'forbidden'; end if;
 if public.pooling_module_enabled(target_client,'r1') is distinct from true then raise exception 'feature_disabled'; end if;
 return jsonb_build_object(
  'manifests',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'state',m.state,'document',m.document) order by m.id) from public.pooling_manifests m where m.state='published' and public.pooling_manifest_allowed(target_client,m.id)),'[]'),
  'decisions',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'draftId',v.draft_id,'generation',v.context_generation,'result',v.result,'validUntil',v.valid_until,'manifestState',m.state) order by v.id desc)
    from public.pooling_decisions v join public.pooling_drafts d on d.id=v.draft_id join public.pooling_manifests m on m.id=v.manifest_id where d.client_id=target_client),'[]'),
  'assignments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'draftId',a.draft_id,'decisionId',a.decision_id,'approvedAt',a.approved_at)) from public.pooling_assignments a where a.client_id=target_client),'[]'));
end $$;

create or replace function public.pooling_request_extension(target_client text,expected_generation bigint,operation_key text,proposal jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; ctx public.pooling_contexts%rowtype; prior public.pooling_extension_requests%rowtype; rid bigint;
begin
 select * into c from public.clients where id=target_client for update;
 if not found or auth.uid() is null or (c."coachId" is distinct from auth.uid() and c."userId" is distinct from auth.uid()) then raise exception 'forbidden'; end if;
 if operation_key is null or length(operation_key) not between 8 and 180 then raise exception 'invalid_operation_key'; end if;
 if proposal is null or jsonb_typeof(proposal)<>'object' or octet_length(proposal::text)>8192 or proposal->>'kind' is null or proposal->>'kind' not in ('daily','progression') then raise exception 'invalid_request'; end if;
 if exists(select 1 from jsonb_object_keys(proposal) k where k not in ('kind','date','requestedChange','blocks','authority','state'))
  or proposal->'blocks' is distinct from '[]'::jsonb or proposal->>'authority' is distinct from 'none' or proposal->>'state' is distinct from 'review_requested'
  or jsonb_typeof(proposal->'requestedChange') is distinct from 'string' or length(trim(proposal->>'requestedChange')) not between 1 and 4000
  or proposal->>'date' is null or proposal->>'date' !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'invalid_request'; end if;
 perform (proposal->>'date')::date;
 select * into prior from public.pooling_extension_requests r where r.client_id=target_client and r.actor_id=auth.uid() and r.operation_key=pooling_request_extension.operation_key;
 if found then
  if prior.proposal is distinct from pooling_request_extension.proposal then raise exception 'idempotency_conflict'; end if;
  return jsonb_build_object('id',prior.id,'status','saved');
 end if;
 if not public.pooling_module_enabled(target_client,case when proposal->>'kind'='daily' then 'r2' else 'r3' end) then raise exception 'feature_disabled'; end if;
 insert into public.pooling_contexts(client_id) values(target_client) on conflict do nothing;
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 if ctx.generation is distinct from expected_generation then raise exception 'stale_context'; end if;
 insert into public.pooling_extension_requests(client_id,actor_id,kind,proposal,generation,operation_key)
 values(target_client,auth.uid(),proposal->>'kind',pooling_request_extension.proposal,ctx.generation,pooling_request_extension.operation_key) returning id into rid;
 return jsonb_build_object('id',rid,'status','saved');
end $$;

create or replace function public.pooling_review_extension(target_client text,request_id bigint,expected_generation bigint,operation_key text,action text,reason text,proposal_id bigint default null,amended_draft jsonb default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype; r public.pooling_extension_requests%rowtype; prior public.pooling_extension_reviews%rowtype; p public.pooling_extension_proposals%rowtype;
 ctx public.pooling_contexts%rowtype; payload jsonb; draft_receipt jsonb; rid bigint; proposed jsonb;
begin
 select * into c from public.clients where id=target_client for update;
 if not found or auth.uid() is null or c."coachId" is distinct from auth.uid() then raise exception 'forbidden'; end if;
 if operation_key is null or length(operation_key) not between 8 and 180 or action is null or action not in ('accept','amend','reject') or reason is null or length(trim(reason)) not between 1 and 4000 then raise exception 'invalid_request'; end if;
 payload:=jsonb_build_object('requestId',request_id,'action',action,'reason',reason,'proposalId',proposal_id,'amendedDraft',amended_draft,'generation',expected_generation);
 select * into prior from public.pooling_extension_reviews v where v.actor_id=auth.uid() and v.client_id=target_client and v.operation_key=pooling_review_extension.operation_key;
 if found then
  if prior.payload is distinct from payload then raise exception 'idempotency_conflict'; end if;
  return jsonb_build_object('id',prior.id,'draftId',prior.draft_id,'status','saved','assignment',null);
 end if;
 select * into r from public.pooling_extension_requests x where x.id=pooling_review_extension.request_id and x.client_id=target_client;
 if not found then raise exception 'forbidden'; end if;
 if not public.pooling_module_enabled(target_client,case when r.kind='daily' then 'r2' else 'r3' end) then raise exception 'feature_disabled'; end if;
 if exists(select 1 from public.pooling_extension_reviews v where v.request_id=r.id) then raise exception 'draft_conflict'; end if;
 select * into ctx from public.pooling_contexts where client_id=target_client for update;
 if ctx.generation is distinct from expected_generation then raise exception 'stale_context'; end if;
 if action='accept' then
  select * into p from public.pooling_extension_proposals x where x.id=proposal_id and x.request_id=r.id;
  if not found then raise exception 'decision_unavailable'; end if;
  perform public.pooling_assert_decision_current(c."coachId",target_client,p.draft_id,p.decision_id);
  if p.source_token is distinct from public.pooling_extension_input(c."coachId",target_client,r.id,p.draft_id,p.baseline_assignment_id,p.policy_id)->>'extensionToken' then raise exception 'source_changed'; end if;
  proposed:=p.result->'suggestedDraft';
  if proposed is null or proposed='null'::jsonb then raise exception 'dose_review_required'; end if;
 elsif action='amend' then proposed:=amended_draft;
 end if;
 if action<>'reject' then
  if ctx.held then raise exception 'context_held'; end if;
  if proposed is null or proposed->>'date' is distinct from r.proposal->>'date' or jsonb_typeof(proposed->'selection') is distinct from 'array' then raise exception 'invalid_proposal'; end if;
  draft_receipt:=public.pooling_save_draft(target_client,expected_generation,operation_key||':draft',proposed);
 end if;
 insert into public.pooling_extension_reviews(request_id,actor_id,client_id,action,reason,draft_id,generation,operation_key,payload)
 values(r.id,auth.uid(),target_client,pooling_review_extension.action,pooling_review_extension.reason,(draft_receipt->>'id')::bigint,expected_generation,pooling_review_extension.operation_key,payload) returning id into rid;
 return jsonb_build_object('id',rid,'draftId',(draft_receipt->>'id')::bigint,'status','saved','assignment',null);
end $$;

create or replace function public.pooling_extension_input(verified_actor uuid,target_client text,target_request bigint,target_draft bigint,baseline_assignment bigint,target_policy text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare snapshot jsonb; r public.pooling_extension_requests%rowtype; a public.pooling_assignments%rowtype; v public.pooling_decisions%rowtype; p jsonb; result jsonb; manifest_doc jsonb;
begin
 snapshot:=public.pooling_decision_input(verified_actor,target_client,target_draft);
 select * into r from public.pooling_extension_requests where id=target_request and client_id=target_client;
 if not found then raise exception 'forbidden'; end if;
 if not public.pooling_module_enabled(target_client,case when r.kind='daily' then 'r2' else 'r3' end) then raise exception 'feature_disabled'; end if;
 select * into a from public.pooling_assignments where id=baseline_assignment and client_id=target_client;
 if not found then raise exception 'forbidden'; end if;
 -- Temporary adjustments are not silently reused as the programme baseline.
 if exists(select 1 from public.pooling_extension_reviews x where x.draft_id=a.draft_id) then raise exception 'baseline_review_required'; end if;
 if exists(select 1 from public.pooling_extension_reviews x where x.request_id=r.id) then raise exception 'draft_conflict'; end if;
 if (select proposal->>'date' from public.pooling_drafts where id=target_draft) is distinct from r.proposal->>'date' then raise exception 'session_mismatch'; end if;
 select * into v from public.pooling_decisions where id=a.decision_id;
 select document into manifest_doc from public.pooling_manifests where id=snapshot->'manifest'->>'id';
 select value into p from jsonb_array_elements(coalesce(manifest_doc->'extensionPolicies','[]')) where value->>'id'=target_policy and value->>'kind'=r.kind;
 if p is null then raise exception 'unsupported_policy'; end if;
 result:=jsonb_build_object('clientId',target_client,'kind',r.kind,'policy',p,'manifest',snapshot->'manifest','held',snapshot->'held','contextInput',snapshot->'contextInput',
   'targetProposal',(select proposal from public.pooling_drafts where id=target_draft),'catalogue',snapshot->'catalogue','doses',snapshot->'doses',
   'baselineBlocks',v.result->'blocks','baselineRevision',a.draft_id,'baselineAssignmentId',a.id,
   'completedOccurrences',(select coalesce(jsonb_agg(distinct e.payload->>'occurrenceId'),'[]') from public.pooling_execution_events e where e.assignment_id=a.id and e.kind='actual'),
   'performances',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id::text,'lineageId',e.id::text,'assignmentId',aa.id,'occurrenceId',e.payload->>'occurrenceId','setIndex',e.payload->'setIndex','expectedSets',b->'dose'->'prescription'->'sets',
      'variantId',b->>'exerciseId','variantRevision',b->'exerciseRevision','side',coalesce(e.payload->>'side','not_applicable'),'loadBasis',case when b->'dose'->'prescription'->'loadKg'='null'::jsonb then '"no_external_load"'::jsonb else jsonb_build_object('unit','kg','value',e.payload->'loadKg') end,
      'range',b->'dose'->'prescription'->'comparison'->'range','equipment',b->'dose'->'prescription'->'comparison'->'equipment','unit',e.payload->>'unit',
      'method',b->'dose'->'prescription'->'comparison'->'method','assistance',b->'dose'->'prescription'->'comparison'->'assistance',
      'actual',e.payload->'actual','quality','confirmed','effortConfirmed',e.payload ?& array['effort','effortMethod'] and nullif(b->'dose'->'prescription'->'comparison'->>'effortMethod','') is not null and e.payload->>'effortMethod'=b->'dose'->'prescription'->'comparison'->>'effortMethod',
      'complete',exists(select 1 from public.pooling_execution_events done where done.assignment_id=aa.id and done.kind='complete' and done.recorded_at<=(snapshot->'contextInput'->>'knowledgeCutoff')::timestamptz),
      'effectiveAt',coalesce(e.payload->>'performedAt',e.recorded_at::text),'recordedAt',e.recorded_at)),'[]')
    from public.pooling_assignments aa join public.pooling_decisions vv on vv.id=aa.decision_id join public.pooling_execution_events e on e.assignment_id=aa.id
    cross join lateral jsonb_array_elements(vv.result->'blocks') b where aa.client_id=target_client and e.kind='actual' and b->>'occurrenceId'=e.payload->>'occurrenceId'
     and e.recorded_at<=(snapshot->'contextInput'->>'knowledgeCutoff')::timestamptz
     and not exists(select 1 from public.pooling_execution_events correction where correction.assignment_id=aa.id and correction.payload->>'supersedes'=e.id::text and correction.recorded_at<=(snapshot->'contextInput'->>'knowledgeCutoff')::timestamptz)),
   'sourceToken',snapshot->>'sourceToken');
 return result||jsonb_build_object('extensionToken',encode(sha256(convert_to(result::text,'UTF8')),'hex'));
end $$;

create or replace function public.pooling_client_home(target_client text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype;
begin
 select * into c from public.clients where id=target_client;
 if not found or auth.uid() is null or (c."coachId" is distinct from auth.uid() and c."userId" is distinct from auth.uid()) then raise exception 'forbidden'; end if;
 if not public.pooling_governed_client(target_client) then raise exception 'feature_disabled'; end if;
 return jsonb_build_object('context',(select jsonb_build_object('generation',generation,'held',held) from public.pooling_contexts where client_id=target_client),
  'reports',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'field',r.field,'value',r.value,'effectiveAt',r.effective_at,'recordedAt',r.recorded_at,'reporterKind',r.reporter_kind) order by r.id desc),'[]') from public.pooling_reports r where r.client_id=target_client and (r.actor_id=auth.uid() or c."coachId"=auth.uid())),
  'classicHistory',(select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'date',w.date,'status',w.status,'durationSeconds',w."durationSec") order by w.date desc),'[]') from public.workouts w where w."clientId"=target_client));
end $$;

create or replace function public.pooling_week_input(verified_actor uuid,target_client text,week_request jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype;ctx public.pooling_contexts%rowtype;slot jsonb;snapshot jsonb;sessions jsonb:='[]';m public.pooling_manifests%rowtype;policy jsonb;result jsonb;tokens jsonb:='[]';
begin
 select * into c from public.clients where id=target_client for update;
 if not found or verified_actor is null or c."coachId" is distinct from verified_actor then raise exception 'forbidden';end if;
 if public.pooling_module_enabled(target_client,'r3') is distinct from true then raise exception 'feature_disabled';end if;
 if week_request is null or jsonb_typeof(week_request)<>'object' or octet_length(week_request::text)>16384 or not(week_request ?& array['manifestId','policyId','constraints']) or exists(select 1 from jsonb_object_keys(week_request) k where k not in ('manifestId','policyId','constraints')) then raise exception 'invalid_week';end if;
 if jsonb_typeof(week_request->'constraints'->'slots') is distinct from 'array' then raise exception 'invalid_week';end if;
 if jsonb_array_length(week_request->'constraints'->'slots') not between 1 and 31 or (select count(distinct s->>'draftId') from jsonb_array_elements(week_request->'constraints'->'slots') s)<>jsonb_array_length(week_request->'constraints'->'slots') then raise exception 'invalid_week';end if;
 select * into ctx from public.pooling_contexts where client_id=target_client;
 select * into m from public.pooling_manifests where id=week_request->>'manifestId' for share;
 if not public.pooling_manifest_allowed(target_client,m.id) then raise exception 'test_scope_mismatch';end if;
 if not found or m.state<>'published' then raise exception 'content_revoked';end if;
 select p into policy from jsonb_array_elements(coalesce(m.document->'extensionPolicies','[]')) p where p->>'id'=week_request->>'policyId' and p->>'kind'='weekly';
 if policy is null then raise exception 'unsupported_policy';end if;
 for slot in select value from jsonb_array_elements(week_request->'constraints'->'slots') loop
  if coalesce(slot->>'draftId','')!~'^[1-9][0-9]*$' then raise exception 'invalid_week';end if;
  snapshot:=public.pooling_decision_input(verified_actor,target_client,(slot->>'draftId')::bigint);
  if snapshot->'manifest'->>'id' is distinct from m.id or (snapshot->'draft'->>'contextGeneration')::bigint is distinct from ctx.generation or exists(select 1 from public.pooling_drafts where parent_id=(slot->>'draftId')::bigint) then raise exception 'stale_draft';end if;
  sessions:=sessions||jsonb_build_array(snapshot);
  tokens:=tokens||jsonb_build_array(jsonb_build_object('draftId',slot->'draftId','sourceToken',snapshot->'sourceToken'));
 end loop;
 result:=jsonb_build_object('clientId',target_client,'generation',ctx.generation,'constraints',week_request->'constraints','sessions',sessions,'policy',policy,'manifest',m.document->'manifest');
 return result||jsonb_build_object('weekToken',encode(sha256(convert_to(jsonb_build_object('request',week_request,'tokens',tokens,'generation',ctx.generation,'manifest',m.document)::text,'UTF8')),'hex'));
end $$;

create or replace function public.pooling_request_reassessment(target_client text,operation_key text,review_request jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c public.clients%rowtype;r public.pooling_reassessment_requests%rowtype;rid bigint;field_name text;
begin
 select * into c from public.clients where id=target_client for update;
 if not found or auth.uid() is null or (c."coachId" is distinct from auth.uid() and c."userId" is distinct from auth.uid()) then raise exception 'forbidden';end if;
 if public.pooling_module_enabled(target_client,'r3') is distinct from true then raise exception 'feature_disabled';end if;
 if operation_key is null or length(operation_key) not between 8 and 180 or review_request is null or jsonb_typeof(review_request)<>'object' or not(review_request ?& array['field','side','protocol','sourceReference','reason']) or exists(select 1 from jsonb_object_keys(review_request) k where k not in ('field','side','protocol','sourceReference','reason')) then raise exception 'invalid_request';end if;
 foreach field_name in array array['field','protocol','sourceReference','reason'] loop
  if jsonb_typeof(review_request->field_name) is distinct from 'string' or length(trim(review_request->>field_name)) not between 1 and 1000 then raise exception 'invalid_request';end if;
 end loop;
 if review_request->>'side' is null or review_request->>'side' not in ('left','right','bilateral','midline','not_applicable') then raise exception 'invalid_request';end if;
 select * into r from public.pooling_reassessment_requests q where q.client_id=target_client and q.actor_id=auth.uid() and q.operation_key=pooling_request_reassessment.operation_key;
 if found then
  if r.request is distinct from review_request then raise exception 'idempotency_conflict';end if;
  return jsonb_build_object('id',r.id,'status','committed','resolvesRestriction',false);
 end if;
 insert into public.pooling_reassessment_requests(client_id,actor_id,operation_key,request) values(target_client,auth.uid(),pooling_request_reassessment.operation_key,review_request) returning id into rid;
 return jsonb_build_object('id',rid,'status','committed','resolvesRestriction',false);
end $$;
notify pgrst,'reload schema';
commit;
