import {useState} from 'react'
import {Link} from 'react-router-dom'
import PoolingAction from '../../molecules/PoolingAction'
import {sessionStartBlock} from '../../../lib/pooling/action-readiness'
import {coachErrorMessage,coachLabel,coachSessionStatus} from '../../../lib/pooling/coach-view'

function SetResult({assignment,block,index,side,workflow,latest,active}){
 const [actual,setActual]=useState(latest?.actual??''),[load,setLoad]=useState(latest?.loadKg??''),[effort,setEffort]=useState(latest?.effort??''),[reason,setReason]=useState('')
 const unit=block.prescription.mode==='repetitions'?'repetitions':'seconds'
 const valid=actual!==''&&Number.isFinite(Number(actual))&&Number(actual)>=0&&(unit!=='repetitions'||Number.isInteger(Number(actual)))&&(load===''||Number(load)>=0)&&(effort===''||(Number(effort)>=1&&Number(effort)<=10))&&(!latest||reason.trim())
 return <div className="coach-set-row"><span>Set {index}{side==='not_applicable'?'':` · ${coachLabel(side)}`}</span><label><span>{unit==='repetitions'?'Reps':'Seconds'}</span><input type="number" min="0" value={actual} disabled={!active} onChange={event=>setActual(event.target.value)}/></label><label><span>Load kg <em>optional</em></span><input type="number" min="0" value={load} disabled={!active} onChange={event=>setLoad(event.target.value)}/></label><label><span>Effort 1–10 <em>optional</em></span><input type="number" min="1" max="10" value={effort} disabled={!active} onChange={event=>setEffort(event.target.value)}/></label>{latest&&<label className="coach-set-reason"><span>Reason for correction</span><input value={reason} disabled={!active} onChange={event=>setReason(event.target.value)}/></label>}<PoolingAction className="btn ghost sm" reason={!active?'Start the session before recording results.':workflow.status==='saving'?'Saving the current result…':!valid?latest?'Enter a valid result and explain the correction.':'Enter the actual result for this set.':''} onClick={()=>workflow.execute(assignment,'actual',{occurrenceId:block.occurrenceId,setIndex:index,side,actual:Number(actual),unit,performedAt:new Date().toISOString(),...(load!==''?{loadKg:Number(load)}:{}),...(effort!==''?{effort:Number(effort),effortMethod:'RPE 1-10'}:{}),...(latest?{supersedes:latest.id,correctionReason:reason.trim()}:{})})}>{latest?'Correct':'Save'}</PoolingAction></div>
}

function Session({assignment,workflow,today}){
 const [health,setHealth]=useState(''),status=coachSessionStatus(assignment,today),active=['start','resume','pause'].includes(assignment.status),localStop=workflow.stopped.includes(assignment.id)
 const canRecord=active&&!localStop, superseded=new Set(assignment.actuals.map(row=>row.supersedes).filter(Boolean))
 const time=assignment.sessionAt?new Intl.DateTimeFormat(undefined,{timeZone:assignment.timeZone||'UTC',hour:'numeric',minute:'2-digit'}).format(new Date(assignment.sessionAt)):''
 return <article className="coach-session-card"><header><div><p className="coach-eyebrow">{assignment.date}{time?` · ${time}`:''}</p><h3>{assignment.blocks.length}-exercise workout</h3></div><span className={`coach-status ${status.tone}`}>{status.label}</span></header>
  {['assigned','start','resume','pause'].includes(assignment.status)&&!assignment.stale&&!assignment.held&&<div className="coach-session-health"><label htmlFor={`coach-health-${assignment.id}`}>Before starting: has anything changed with the client’s health?</label><select id={`coach-health-${assignment.id}`} value={health} onChange={event=>setHealth(event.target.value)}><option value="">Choose an answer</option><option value="no_change">No change reported</option><option value="changed">Something changed or there is a concern</option><option value="declined">Client preferred not to answer</option></select>{['changed','declined'].includes(health)&&<button className="btn" disabled={workflow.status==='saving'} onClick={()=>workflow.reportHealth(assignment,health)}>Save for coach review</button>}{['assigned','pause'].includes(assignment.status)&&<PoolingAction reason={sessionStartBlock({assignment,workflow,localStop,health})} onClick={()=>{const value=health;setHealth('');workflow.execute(assignment,assignment.status==='pause'?'resume':'start',{healthChange:value})}}>{assignment.status==='pause'?'Resume session':'Start session'}</PoolingAction>}</div>}
  {(assignment.stale||assignment.held)&&!['complete','stop'].includes(assignment.status)&&<div className="coach-inline-warning"><strong>This workout needs a new review before it can start.</strong><Link to="pool">Prepare an updated workout</Link></div>}
  <div className="coach-session-exercises">{assignment.blocks.map((block,number)=>{
   const rows=Array.from({length:block.prescription.sets},(_,setIndex)=>(block.prescription.sideMultiplier===2?['left','right']:['not_applicable']).map(side=>({setIndex:setIndex+1,side}))).flat()
   return <section key={block.occurrenceId}><div className="coach-session-exercise-head"><span>{number+1}</span><div><small>{coachLabel(block.role)}</small><h4>{block.exerciseName||'Exercise'}</h4><p>{block.prescription.sets} sets · {block.prescription.mode==='repetitions'?`${block.prescription.reps} reps`:`${block.prescription.workSeconds} sec`}{block.prescription.sideMultiplier===2?' each side':''} · Rest {block.prescription.restSeconds} sec</p></div></div>{assignment.status!=='assigned'&&<details><summary>{assignment.status==='complete'?'View or correct results':'Record results'}</summary>{rows.map(({setIndex,side})=>{const latest=assignment.actuals.find(row=>row.occurrenceId===block.occurrenceId&&row.setIndex===setIndex&&(row.side||'not_applicable')===side&&!superseded.has(row.id));return <SetResult key={`${setIndex}:${side}:${latest?.id||'new'}`} assignment={assignment} block={block} index={setIndex} side={side} workflow={workflow} latest={latest} active={canRecord||assignment.status==='complete'}/>})}</details>}</section>
  })}</div>
  {active&&<div className="coach-session-actions"><button className="btn danger" onClick={()=>workflow.execute(assignment,'stop')}>Stop now</button><PoolingAction className="btn ghost" reason={assignment.status==='pause'?'This session is already paused.':workflow.status==='saving'?'Wait for the current save.':''} onClick={()=>workflow.execute(assignment,'pause')}>Pause</PoolingAction><PoolingAction reason={workflow.status==='saving'?'Wait for the current save.':workflow.pending?'Check the previous save first.':''} onClick={()=>workflow.execute(assignment,'complete')}>Finish session</PoolingAction></div>}
  {assignment.status==='complete'&&<p className="coach-complete-note">Completed · {assignment.actuals.filter(row=>!superseded.has(row.id)).length} results recorded</p>}
 </article>
}

export default function CoachSessionPanel({workflow,today}){
 return <section id="workouts" className="coach-card"><div className="coach-card-head"><div><p className="coach-eyebrow">Assigned and completed</p><h2>Workouts</h2></div><button className="coach-text-button" onClick={workflow.refresh} disabled={workflow.status==='saving'}>Refresh</button></div>
  {workflow.error&&<div className="coach-error" role="alert">{coachErrorMessage({message:workflow.error})}</div>}{workflow.pending&&<button className="btn" onClick={workflow.retry} disabled={workflow.status==='saving'}>Check previous save</button>}
  {!workflow.assignments.length&&workflow.status!=='loading'&&<div className="coach-empty-state"><strong>No workouts assigned yet</strong><p>Prepare a workout, review it and approve the assignment.</p></div>}
  {workflow.status==='loading'&&<p role="status">Loading workouts…</p>}
  <div className="coach-session-list">{workflow.assignments.map(item=><Session key={item.id} assignment={item} workflow={workflow} today={today}/>)}</div>
 </section>
}
