import { test } from 'node:test'
import assert from 'node:assert/strict'
import { builderDraft, readLocalDrafts, saveLocalDraft, LOCAL_DRAFT_KEY } from '../../src/lib/pooling/drafts.js'
const store = () => { const data = new Map(); return { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, value) } }
const operation = () => ({ clientId: 'synthetic-a', operationKey: 'test-key', expectedRevision: 0, recordedAt: '2026-09-07T12:00:00Z', proposal: { date: '2026-09-07', blocks: [] } })
test('invalid calendar day is rejected', () => assert.throws(()=>builderDraft({date:'2026-02-31',blocks:[]}),/invalid_date/))
test('local draft survives store reload with no authority', () => { const storage = store(); const receipt = saveLocalDraft(storage,operation()); assert.equal(receipt.authority,'none'); assert.equal(readLocalDrafts(storage).records.length,1) })
test('retry is idempotent; changed payload rejected', () => { const storage=store(); const input=operation(); const first=saveLocalDraft(storage,input); assert.deepEqual(saveLocalDraft(storage,input),first); input.proposal.blocks=[1]; assert.throws(()=>saveLocalDraft(storage,input),/idempotency_conflict/) })
test('stale tab cannot overwrite newer draft', () => { const storage=store(); saveLocalDraft(storage,operation()); assert.throws(()=>saveLocalDraft(storage,{...operation(),operationKey:'other'}),/draft_conflict/); assert.equal(readLocalDrafts(storage).records.length,1) })
test('quota failure is not successful save', () => { const storage=store(); storage.setItem=()=>{throw new Error('quota')}; assert.throws(()=>saveLocalDraft(storage,operation()),/quota/) })
test('corrupt storage never silently resets', () => { const storage=store(); storage.setItem(LOCAL_DRAFT_KEY,'broken'); assert.throws(()=>saveLocalDraft(storage,operation()),/corrupt/); assert.equal(storage.getItem(LOCAL_DRAFT_KEY),'broken') })
test('copy/import strips approval, actuals and private cross-client notes', () => { const input={date:'2026-09-07',crossClient:true,notes:'private',blocks:[{blockId:'b',approval:true,exercises:[{exerciseId:'e',clinicalNote:'private',sets:[{setId:'s',prescribedReps:0,completedReps:10,status:'Completed',approvedBy:'someone'}]}]}]}; const draft=builderDraft(input); assert.equal(draft.notes,''); assert.equal(draft.blocks[0].approval,undefined); assert.equal(draft.blocks[0].exercises[0].clinicalNote,undefined); assert.equal(draft.blocks[0].exercises[0].sets[0].prescribedReps,0); assert.equal(draft.blocks[0].exercises[0].sets[0].completedReps,null); assert.equal(input.blocks[0].exercises[0].sets[0].completedReps,10) })
