import {test} from 'node:test'
import assert from 'node:assert/strict'
import {OPERATION_KEY,pendingOperations,prepareOperation,settleOperation,rejectOperation} from '../../src/lib/pooling/operations.js'
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}}
test('write-ahead operation keeps exact request across reload/retry',()=>{const s=storage(),entry={scope:'coach:c1',kind:'draft',request:{operationKey:'op-key',proposal:{value:0}}};prepareOperation(s,entry);assert.deepEqual(pendingOperations(s,entry.scope)[0].request,entry.request);assert.equal(pendingOperations(s,'coach:c2').length,0);assert.throws(()=>prepareOperation(s,{...entry,request:{...entry.request,proposal:{value:1}}}),/idempotency_conflict/)})
test('receipt journal never clears unknown operations prematurely',()=>{const s=storage();prepareOperation(s,{scope:'a',kind:'draft',request:{operationKey:'op-key'}});assert.throws(()=>settleOperation(s,'a','op-key',{status:'not_found'}),/invalid_receipt/);assert.equal(pendingOperations(s,'a').length,1);settleOperation(s,'a','op-key',{status:'saved',id:1});assert.equal(pendingOperations(s,'a').length,0)})
test('quota or corrupt journal is a failure, not a new empty operation list',()=>{assert.throws(()=>prepareOperation({getItem:()=>null,setItem:()=>{throw Error('quota')}},{scope:'a',kind:'draft',request:{operationKey:'op-key'}}),/quota/);assert.throws(()=>pendingOperations({getItem:()=>'{broken'},'a'),/corrupt/)})
test('a definitive rejection cannot be silently resent as a fresh operation',()=>{const s=storage(),entry={scope:'a',kind:'draft',request:{operationKey:'op-key'}};prepareOperation(s,entry);rejectOperation(s,'a','op-key','stale_context');assert.throws(()=>prepareOperation(s,entry),/stale_context/);assert.equal(pendingOperations(s,'a').length,0)})
test('malformed journal rows are preserved, not adopted or erased',()=>{const s=storage(),raw=JSON.stringify({schemaVersion:1,operations:[{scope:'a'}]});s.setItem(OPERATION_KEY,raw);assert.throws(()=>pendingOperations(s,'a'),/unsupported/);assert.equal(s.getItem(OPERATION_KEY),raw)})
