import test from 'node:test'
import assert from 'node:assert/strict'
import {aggregatePerformances} from '../../src/lib/pooling/performance-history.js'
function fixture(){const row={id:'1',assignmentId:1,occurrenceId:'one',setIndex:1,expectedSets:2,variantId:'test',variantRevision:1,side:'left',range:'test',equipment:[],unit:'seconds',method:'test',assistance:'none',loadBasis:'no_external_load',quality:'confirmed',complete:true,effortConfirmed:true,actual:1,recordedAt:'2026-09-07T12:00:00Z',effectiveAt:'2026-09-07T11:00:00Z'};return {performances:[row,{...row,id:'2',setIndex:2,actual:2}],policy:{performanceUnit:'completed_occurrence',aggregation:'minimum_actual'},knowledgeCutoff:'2026-09-07T12:00:00Z',sessionAt:'2026-09-07T12:00:00Z'}}
test('two sets from one occurrence count as one comparable performance',()=>{const r=aggregatePerformances(fixture());assert.equal(r.performances.length,1);assert.equal(r.performances[0].actual,1);assert.equal(r.performances[0].complete,true)})
test('missing sets cannot be populated from prescription',()=>{const i=fixture();i.performances.pop();const r=aggregatePerformances(i).performances[0];assert.equal(r.complete,false);assert.equal(r.actual,null)})
test('a different side cannot supply the missing second set',()=>{const i=fixture();i.performances[1].side='right';assert(aggregatePerformances(i).performances.every(r=>!r.complete))})
test('unknown effort or conflicting revision cannot support an increase',()=>{const i=fixture();i.performances[1].effortConfirmed=false;assert.equal(aggregatePerformances(i).performances[0].effortConfirmed,false);i.performances[1].variantRevision=2;assert.equal(aggregatePerformances(i).performances[0].complete,false)})
test('aggregation must be supplied by a reviewed policy',()=>{const i=fixture();i.policy.aggregation=null;assert.equal(aggregatePerformances(i).state,'unsupported_policy')})
test('later known evidence is excluded from a historical comparison',()=>{const i=fixture();i.performances[1].recordedAt='2026-09-08T12:00:00Z';assert.equal(aggregatePerformances(i).performances[0].complete,false)})
